[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.3.0"

[[constraint]]
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.16.10"

[prune]
  go-tests = true
  unused-packages = true
